# Generated by Django 4.0.5 on 2022-07-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageanswer',
            name='image',
        ),
        migrations.AddField(
            model_name='imageanswer',
            name='image_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
